name: Upgrade Academies

on:
  release:
    types: [published]

jobs:
  bump:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependent-repo:
          - layer5io/layer5-academy
          - layer5io/exoscale-academy
          - layer5io/academy-build
          - layer5io/academy-example
    steps:
      - name: Checkout academy-theme code 
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Checkout dependent repo
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.dependent-repo }}
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          path: dependent
          ref: master

      - name: Update dependency in go.mod
        run: |
          cd dependent
          make theme-update
          # go mod edit -require=github.com/layer5io/academy-theme@${{ github.event.release.tag_name }}
          # go mod tidy

      - name: Create Pull pull-requests
        uses: peter-evans/create-pull-request@v7
        with:
          path: dependent
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          branch: update-academy-theme-${{ github.event.release.tag_name }}
          title: '[Automated] Update academy-theme to ${{ github.event.release.tag_name }}'
          body: |
            This PR updates the academy-theme dependency to the latest release version ${{ github.event.release.tag_name }}.

            Changes:
            - Updated go.mod
            - Regenerated go.sum

            Auto-generated based upon release of a new version of layer5io/academy-theme.
          commit-message: Update academy-theme to ${{ github.event.release.tag_name }}
          committer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: true
          delete-branch: true
          labels: pr/dependencies
          assignees: l5io
          draft: false
